steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/ai-image-repo/ml-healthy-vs-rotten-classification-model',
    '-f',
    'dockerfiles/train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/ai-image-repo/ml-healthy-vs-rotten-classification-model'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build evaluate container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/ai-image-repo/ml-healthy-vs-rotten-evaluate-model',
    '-f',
    'dockerfiles/evaluate.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push evaluate container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/ai-image-repo/ml-healthy-vs-rotten-evaluate-model'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build API container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/ai-image-repo/ml-healthy-vs-rotten-api',
    '-f',
    'dockerfiles/api.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push API container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/ai-image-repo/ml-healthy-vs-rotten-api'
  ]
logsBucket: "gs://ml-ops-healthy-vs-rotten-data/" 